# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cobess_one_inner <- function(X, Y, A0, B0, A, B, C, r = 3L, kx = 10L, ky = 3L, eps = 0.001, maxit = 10L, inner_maxit = 10L, rho = 1.0) {
    .Call(`_csrrr_cobess_one_inner`, X, Y, A0, B0, A, B, C, r, kx, ky, eps, maxit, inner_maxit, rho)
}

cobess_one <- function(X, Y, A0, B0, r = 3L, kx = 10L, ky = 3L, eps = 0.001, maxit = 10L, inner_maxit = 10L, rho = 1.0, normalize = TRUE) {
    .Call(`_csrrr_cobess_one`, X, Y, A0, B0, r, kx, ky, eps, maxit, inner_maxit, rho, normalize)
}

cobess_r_inner <- function(X, Y, A, C, ICmat, rowmin, colmin, kx_max, ky_max, r = 3L, eps = 1e-3, maxit = 10L, inner_maxit = 10L, warm_start = TRUE, opt = 'A', rho = 1.0) {
    .Call(`_csrrr_cobess_r_inner`, X, Y, A, C, ICmat, rowmin, colmin, kx_max, ky_max, r, eps, maxit, inner_maxit, warm_start, opt, rho)
}

cobess_r <- function(X, Y, kx_max, ky_max, r = 3L, eps = 0.001, maxit = 10L, inner_maxit = 10L, warm_start = TRUE, opt = 'A', rho = 1.0, normalize = TRUE) {
    .Call(`_csrrr_cobess_r`, X, Y, kx_max, ky_max, r, eps, maxit, inner_maxit, warm_start, opt, rho, normalize)
}

cobessC <- function(X, Y, r_max, kx_max, ky_max, sigma = -1.0, eps = 0.001, maxit = 10L, inner_maxit = 10L, warm_start = TRUE, opt = 'A', rho = 1.0, normalize = TRUE) {
    .Call(`_csrrr_cobessC`, X, Y, r_max, kx_max, ky_max, sigma, eps, maxit, inner_maxit, warm_start, opt, rho, normalize)
}

mrbess_one <- function(X, Y, A0, B0, r = 3L, p0 = 10L, eps = 0.001, maxit = 100L, inner_maxit = 10L, rho = 1.0) {
    .Call(`_csrrr_mrbess_one`, X, Y, A0, B0, r, p0, eps, maxit, inner_maxit, rho)
}

nmrbess_one <- function(X, Y, A0, B0, X_gen, x_norm, r, lam, L, p0, eps = 0.001, maxit = 100L, inner_maxit = 10L) {
    .Call(`_csrrr_nmrbess_one`, X, Y, A0, B0, X_gen, x_norm, r, lam, L, p0, eps, maxit, inner_maxit)
}

mrbess_rNull <- function(X, Y, A0, B0, L, X_gen, x_norm, p0_max, lam = 0.0, sigma = -1.0, r = 3L, eps = 1e-3, maxit = 100L, inner_maxit = 10L, warm_start = TRUE, opt = 'A', rho = 1.0) {
    .Call(`_csrrr_mrbess_rNull`, X, Y, A0, B0, L, X_gen, x_norm, p0_max, lam, sigma, r, eps, maxit, inner_maxit, warm_start, opt, rho)
}

mrbess_rnotNull <- function(X, Y, A0, B0, L, X_gen, x_norm, r_max, p0_max, lam = 0.0, sigma = -1.0, eps = 1e-3, maxit = 100L, inner_maxit = 10L, warm_start = TRUE, opt = 'A', size_max = 1e6L, rho = 1.0) {
    .Call(`_csrrr_mrbess_rnotNull`, X, Y, A0, B0, L, X_gen, x_norm, r_max, p0_max, lam, sigma, eps, maxit, inner_maxit, warm_start, opt, size_max, rho)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_csrrr_RcppExport_registerCCallable', PACKAGE = 'csrrr')
})
